---
swagger: 2.0
basePath:
info:
  title: AwsSamExample
schemes:
- http
paths:
  '/fruits':
    x-amazon-apigateway-any-method:
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          schema:
            $ref: "#/definitions/Empty"

      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations"
        httpMethod: POST
        type: aws_proxy
definitions:
  Empty:
    type: object
    title: Empty Schema