AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam api'

Globals:
    Function:
        Timeout: 3

Resources:

    ApiGatewayApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Local
            DefinitionBody:
                'Fn::Transform':
                    Name: 'AWS::Include'
                    Parameters:
                        Location: ./swagger.yaml

    LambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: app.handler
            Runtime: nodejs8.10